### PR TITLE
Added majors-total attribute

### PR DESCRIPTION
**Pull request by lhas**

### CODE REVIEW

**Comment by lhas** [comment]
Its works just like:


              <ds-widget-clock majors-total="24"></ds-widget-clock>

This way, you can set dynamically the majors pointers count. I needed this for a project so i decided to create a PR for this.

**Comment by deepu105** [comment]
Ok ill test and merge

Thanks & regards,
Deepu

**Comment by lhas** [comment]
Nice, @deepu105 ! Thanks for the merge.

**Comment by deepu105** [comment]
can you update the documentation page as well?

**Comment by deepu105** [comment]
So that I can release a new version with this

**Pull request merged**
